name: CI Setup
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USER}}
          key: ${{secrets.SERVER_SSH_KEY}}
          script: |
            cd "C:\Apache24\htdocs"
            git pull origin main
