name: CI Setup
on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Deploy to Apache Directory
        run: |
            cd "C:\Apache24\htdocs"
            git pull origin main
